"""
Netlist Generator — Photonic Circuit Netlist Output
====================================================

Generates human-readable and machine-parseable photonic netlists
from compiled MZI phase configurations.

Output formats:
1. PNTL (Photonic Netlist) — our custom format, SPICE-inspired
2. JSON — for toolchain interoperability
3. SVG — for visualization
4. GDS — (future, requires gdsfactory)

The netlist is the intermediate representation between our compiler
and physical chip layout tools (Cadence Virtuoso, KLayout, gdsfactory).
"""

import json
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Dict, TextIO

from .mzi_mapper import CompiledLayer
from .phase_encoder import PhaseMap

logger = logging.getLogger(__name__)


PNTL_HEADER = """\
# PhotoMedGemma Photonic Netlist v1.0
# Generated by the PhotoMedGemma Compiler
# Platform: 220nm Silicon-on-Insulator
# Wavelength: 1310 nm
# Reference: Clements et al., Optica 3, 1460 (2016)
#
# Format:
#   .model MZI_CELL theta=<rad> phi=<rad>
#   .subckt <name> N=<modes> R=<rank>
#   X_<row>_<col> <mode_i> <mode_j> MZI theta=<rad> phi=<rad>
#   X_D_<i> <mode_i> PHASE_SCREEN phase=<rad>
#   .ends <name>
#
"""


class NetlistGenerator:
    """
    Generates photonic netlists from compiled layers.

    The netlist describes the complete photonic circuit:
    - Each MZI with its phase angles
    - The interconnection topology (Clements mesh)
    - Sigma (attenuator) stages
    - Assembly of complete SVD layers

    This netlist can be:
    1. Used as input to physical layout tools (gdsfactory)
    2. Simulated in photonic circuit simulators (Photontorch, Simphony)
    3. Used directly for chip programming (via phase_encoder)
    """

    def __init__(self, output_dir: str = "netlists"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_layer_netlist(
        self,
        compiled_layer: CompiledLayer,
        filename: Optional[str] = None,
    ) -> str:
        """
        Generate PNTL netlist for a single compiled layer.

        Args:
            compiled_layer: CompiledLayer from MZIMapper
            filename: Output file path. If None, returns as string.

        Returns:
            PNTL netlist string
        """
        lines = [PNTL_HEADER]

        layer = compiled_layer
        safe_name = layer.layer_name.replace(".", "_").replace("/", "_")

        lines.append(f"# Layer: {layer.layer_name}")
        lines.append(f"# Component: {layer.component}")
        lines.append(f"# Projection: {layer.projection_type}")
        lines.append(f"# Transformer layer: {layer.transformer_layer_idx}")
        lines.append(f"# Rank: {layer.rank}")
        lines.append(f"# Total MZIs: {layer.total_mzis:,}")
        lines.append("")

        # V† subcircuit
        lines += self._generate_mesh_subcircuit(
            layer.Vh_mesh.result.mzis,
            layer.Vh_mesh.result.phase_screen,
            layer.Vh_mesh.N,
            layer.rank,
            name=f"{safe_name}_Vh",
            chip_id=layer.chip_id_Vh,
        )

        # Sigma (attenuator) subcircuit
        lines += self._generate_sigma_subcircuit(
            layer.sigma_stage.normalized_sv,
            name=f"{safe_name}_SIGMA",
        )

        # U subcircuit
        lines += self._generate_mesh_subcircuit(
            layer.U_mesh.result.mzis,
            layer.U_mesh.result.phase_screen,
            layer.U_mesh.N,
            layer.rank,
            name=f"{safe_name}_U",
            chip_id=layer.chip_id_U,
        )

        # Top-level assembly
        lines += self._generate_top_assembly(
            safe_name,
            layer.Vh_mesh.N,
            layer.U_mesh.N,
            layer.rank,
        )

        netlist = "\n".join(lines)

        if filename:
            output_path = self.output_dir / filename
            with open(output_path, 'w') as f:
                f.write(netlist)
            logger.info(f"Netlist written to {output_path}")

        return netlist

    def _generate_mesh_subcircuit(
        self,
        mzis,
        phase_screen,
        N: int,
        rank: int,
        name: str,
        chip_id: int,
    ) -> List[str]:
        """Generate PNTL subcircuit for a Clements mesh."""
        lines = []
        lines.append(f".subckt {name} N={N} R={rank} CHIP={chip_id}")
        lines.append(f"* Clements MZI mesh: {N}×{N} unitary, rank-{rank} truncation")
        lines.append(f"* Number of MZIs: {len(mzis)}")
        lines.append("")

        # Group MZIs by column (mesh stage)
        if mzis:
            max_col = max(m.col for m in mzis)
            for col in range(max_col + 1):
                stage_mzis = [m for m in mzis if m.col == col]
                if stage_mzis:
                    lines.append(f"* Stage {col}")
                    for m in sorted(stage_mzis, key=lambda x: x.row):
                        lines.append(
                            f"X_{m.row}_{m.col}  "
                            f"w{m.mode_i}  w{m.mode_j}  "
                            f"MZI  theta={m.theta:.8f}  phi={m.phi:.8f}"
                        )
                    lines.append("")

        # Phase screen
        lines.append("* Diagonal phase screen")
        for i, phase in enumerate(phase_screen):
            lines.append(
                f"X_PS_{i}  w{i}  PHASE_SCREEN  phase={phase:.8f}"
            )

        lines.append(f".ends {name}")
        lines.append("")
        return lines

    def _generate_sigma_subcircuit(
        self,
        normalized_sv: "np.ndarray",
        name: str,
    ) -> List[str]:
        """Generate PNTL subcircuit for the sigma (attenuator) stage."""
        import numpy as np

        lines = []
        rank = len(normalized_sv)
        lines.append(f".subckt {name} R={rank}")
        lines.append(f"* Singular value attenuator stage")
        lines.append(f"* Modes 0..{rank-1}: attenuated by singular values")
        lines.append(f"* Modes {rank}+: blocked (σ=0)")
        lines.append("")

        for i, sv in enumerate(normalized_sv):
            att_db = -20 * np.log10(sv + 1e-15)
            att_db = max(0, min(att_db, 60))
            lines.append(
                f"X_S_{i}  sig{i}  ATTENUATOR  "
                f"value={sv:.8f}  att_db={att_db:.2f}"
            )

        lines.append(f".ends {name}")
        lines.append("")
        return lines

    def _generate_top_assembly(
        self,
        safe_name: str,
        n_in: int,
        n_out: int,
        rank: int,
    ) -> List[str]:
        """Generate top-level subcircuit assembling V† → Σ → U."""
        lines = []
        lines.append(f".subckt {safe_name}_LAYER IN[0:{n_in-1}] OUT[0:{n_out-1}]")
        lines.append(f"* Full SVD layer: V†_mesh → Sigma → U_mesh")
        lines.append("")

        lines.append(
            f"X_Vh  IN[0:{n_in-1}]    {safe_name}_Vh    "
            f"MID_Vh[0:{n_in-1}]"
        )
        lines.append(
            f"X_SIG MID_Vh[0:{rank-1}]   {safe_name}_SIGMA  "
            f"MID_SIG[0:{rank-1}]"
        )
        lines.append(
            f"X_U   MID_SIG[0:{n_out-1}]  {safe_name}_U  "
            f"OUT[0:{n_out-1}]"
        )

        lines.append(f".ends {safe_name}_LAYER")
        lines.append("")
        return lines

    def generate_full_model_netlist(
        self,
        compiled_layers: List[CompiledLayer],
        output_file: str = "medgemma_photonic.pntl",
    ) -> str:
        """
        Generate a single combined netlist for the full model.

        Args:
            compiled_layers: All compiled layers (from MZIMapper)
            output_file: Output filename

        Returns:
            Combined PNTL netlist string
        """
        lines = [PNTL_HEADER]
        lines.append(f"# Full MedGemma Photonic Netlist")
        lines.append(f"# Layers compiled: {len(compiled_layers)}")
        lines.append(f"# Total MZIs: {sum(l.total_mzis for l in compiled_layers):,}")
        lines.append("")

        for layer in compiled_layers:
            layer_netlist = self.generate_layer_netlist(layer)
            lines.append(layer_netlist)

        # Generate top-level model assembly
        lines += self._generate_model_top(compiled_layers)

        combined = "\n".join(lines)

        output_path = self.output_dir / output_file
        with open(output_path, 'w') as f:
            f.write(combined)

        logger.info(
            f"Full model netlist written to {output_path} "
            f"({len(combined.splitlines()):,} lines)"
        )
        return combined

    def _generate_model_top(self, layers: List[CompiledLayer]) -> List[str]:
        """Generate the top-level model instantiation."""
        lines = [
            "",
            "* ============================================================",
            "* Top-level PhotoMedGemma model assembly",
            "* ============================================================",
            ".subckt PHOTOMEDGEMMA",
        ]

        for layer in layers:
            safe_name = layer.layer_name.replace(".", "_").replace("/", "_")
            n_in = layer.Vh_mesh.N
            n_out = layer.U_mesh.N
            lines.append(
                f"X_{safe_name}  "
                f"IN_{safe_name}[0:{n_in-1}]  "
                f"{safe_name}_LAYER  "
                f"OUT_{safe_name}[0:{n_out-1}]"
            )

        lines.append(".ends PHOTOMEDGEMMA")
        lines.append("")
        return lines

    def generate_json_manifest(
        self,
        compiled_layers: List[CompiledLayer],
        phase_map: Optional[PhaseMap] = None,
        output_file: str = "manifest.json",
    ) -> dict:
        """
        Generate a JSON manifest of all compiled layers.

        Useful for toolchain interoperability (gdsfactory, custom simulators).

        Args:
            compiled_layers: All compiled layers
            phase_map: Optional PhaseMap for DAC code inclusion
            output_file: Output filename

        Returns:
            Manifest dictionary
        """
        manifest = {
            "format": "PhotoMedGemma JSON Manifest v1.0",
            "model": "google/medgemma-4b-it",
            "n_layers": len(compiled_layers),
            "total_mzis": sum(l.total_mzis for l in compiled_layers),
            "layers": [],
        }

        for layer in compiled_layers:
            layer_entry = {
                "name": layer.layer_name,
                "component": layer.component,
                "projection_type": layer.projection_type,
                "transformer_layer_idx": layer.transformer_layer_idx,
                "rank": layer.rank,
                "input_dim": layer.Vh_mesh.N,
                "output_dim": layer.U_mesh.N,
                "n_mzis_Vh": layer.n_mzis_Vh,
                "n_mzis_U": layer.n_mzis_U,
                "chip_id_Vh": layer.chip_id_Vh,
                "chip_id_U": layer.chip_id_U,
                "reconstruction_error_svd": layer.reconstruction_error_svd,
                "reconstruction_error_clements_U": layer.reconstruction_error_clements_U,
                "reconstruction_error_clements_Vh": layer.reconstruction_error_clements_Vh,
            }
            manifest["layers"].append(layer_entry)

        output_path = self.output_dir / output_file
        with open(output_path, 'w') as f:
            json.dump(manifest, f, indent=2)

        logger.info(f"JSON manifest written to {output_path}")
        return manifest
